import time
import threading
import sys

# Hardware Abstractions
from hardware.motors import MotorController
from hardware.sensors import SensorArray, UltrasonicSensor
from hardware.servo import CameraServo

# Vision
from vision.predict import VisionSystem

# Web App
import app

# Config
import config

# Main State Machine
class AutonomousRover:
    def __init__(self):
        print("Initializing Hardware...")
        self.motors = MotorController()
        self.ir_array = SensorArray()
        self.ultrasonic = UltrasonicSensor()
        self.servo = CameraServo()
        
        print("Initializing Vision System...")
        # Point to the TFLite model generated by train_model.py
        self.vision = VisionSystem(
            model_path=r"C:\Kriti\AutonomousRover\ml_pipeline\rover_vision_model.tflite",
            labels_path=r"C:\Kriti\AutonomousRover\ml_pipeline\labels.json"
        )
        
        # Link Vision to the Flask Web App
        app.vision_system = self.vision
        
        self.start_time = time.time()
        self.state = "Idle"
        self.running = False
        
        # PID constants (Tune these via physical testing)
        self.Kp = 15.0
        self.Kd = 5.0
        self.last_error = 0

    def start_web_dashboard(self):
        # Start Flask app in a daemon thread
        dashboard_thread = threading.Thread(target=app.start_server, daemon=True)
        dashboard_thread.start()
        print(f"Dashboard started on port {config.FLASK_PORT}")

    def scan_checkpoint(self):
        """Logic for handling the '+' intersection marker"""
        self.set_state("Checkpoint Scanning")
        # Rolling scan! Creep forward slowly instead of parking to save time
        self.motors.forward(int(config.DEFAULT_SPEED * 0.4))
        
        # 1. Left Peripheral Scan
        self.servo.set_angle(-45)
        time.sleep(0.4) # Faster scan interval
        
        # 2. Center Scan
        self.servo.set_angle(0)
        time.sleep(0.4)
        
        # 3. Right Peripheral Scan
        self.servo.set_angle(45)
        time.sleep(0.4)
        
        # Reset Camera Forward
        self.servo.set_angle(0)
        
        # Drive forward slightly to clear the intersection sensor markers
        self.set_state("Clearing Intersection")
        self.motors.forward(config.DEFAULT_SPEED)
        time.sleep(0.4) 

    def avoid_obstacle(self):
        """
        Complex Obstacle Avoidance Maneuver (Off-roading limit <= 10s)
        The rover diverges from the path at the RED block, navigates towards the '+' marker, 
        scans for images, and rejoins the tape path on the other side.
        """
        start_maneuver = time.time()
        self.motors.stop()
        time.sleep(0.3)
        
        # 1. Back up slightly from the obstacle block
        self.motors.backward(config.DEFAULT_SPEED)
        time.sleep(0.4)
        
        # 2. Hard Right Turn (Diverging off-road towards the '+' area)
        self.motors.turn_right(config.TURN_SPEED)
        time.sleep(0.6) # Pre-calibrated 90-degree turn pulse
        
        # 3. Drive forward off-road parallel to the obstacle
        self.motors.forward(config.DEFAULT_SPEED)
        time.sleep(1.2)
        
        # 4. Turn Left to face the '+' location from the side
        self.motors.turn_left(config.TURN_SPEED)
        time.sleep(0.6)
        
        # 5. Drive right up to the '+' marker
        self.motors.forward(config.DEFAULT_SPEED)
        time.sleep(0.8)
        
        # 6. Execute the Image Scanning Routine natively while off-road
        self.scan_checkpoint()
        
        # 7. Resume the hook maneuver to rejoin the line
        self.motors.forward(config.DEFAULT_SPEED)
        time.sleep(1.0) # Finish passing the obstacle block footprint
        
        # 8. Turn Left back toward the original track axis
        self.motors.turn_left(config.TURN_SPEED)
        time.sleep(0.6)
        
        # 9. Drive Forward until the QTR-8RC detects the black line again
        self.motors.forward(max(40, config.DEFAULT_SPEED - 10)) # Slower re-entry
        
        # Fallback 10-second off-road maximum enforcement timer
        while self.ir_array.get_position_error() == "LOST":
            if (time.time() - start_maneuver) > 9.5: 
                print("Warning: Approaching 10s off-road limit. Forcing stop.")
                break
            time.sleep(0.05)
            
        # Rejoined! The while loop in run() will instantly take back over with PID
        self.motors.stop()
        print(f"Obstacle cleared and line rejoined in {round(time.time() - start_maneuver, 2)} seconds.")

    def update_telemetry(self):
        """Update the shared dictionary for the Web Dashboard"""
        app.robot_state["status"] = self.state
        app.robot_state["run_time"] = time.time() - self.start_time

    def set_state(self, new_state):
        if self.state != new_state:
            print(f"State Change: {self.state} -> {new_state}")
            self.state = new_state
            self.update_telemetry()

    def run(self):
        print("Starting Rover Core Loop...")
        self.vision.start()
        self.start_web_dashboard()
        
        self.running = True
        self.start_time = time.time()
        
        try:
            while self.running:
                self.update_telemetry()
                
                # Priority 1: Obstacle Avoidance (Ultrasonic)
                if config.ENABLE_OBSTACLE_AVOIDANCE and self.ultrasonic.is_obstacle_ahead():
                    self.set_state("Avoiding Obstacle (Red Block)")
                    self.avoid_obstacle()
                    continue

                # Priority 2: Line Following (IR Array)
                error = self.ir_array.get_position_error()
                
                if error == "INTERSECTION":
                    # Found the "+" Target
                    self.scan_checkpoint()
                    
                elif error == "LOST":
                    self.set_state("Recovering Path")
                    # simple recovery: reverse to find line again
                    self.motors.backward(config.DEFAULT_SPEED - 10)
                    
                else:
                    self.set_state("Following Path")
                    # PID Control
                    derivative = error - self.last_error
                    motor_adjust = (self.Kp * error) + (self.Kd * derivative)
                    
                    # INVERTED COMPENSATION: Since the physical motors are reversed, 
                    # pushing the right wheel faster requires subtracting from it.
                    left_motor = config.DEFAULT_SPEED - motor_adjust
                    right_motor = config.DEFAULT_SPEED + motor_adjust
                    
                    # Constrain and apply
                    self.motors.move(left_motor, right_motor)
                    self.last_error = error
                    
                # Loop rate limiting
                time.sleep(0.02)
                
        except KeyboardInterrupt:
            print("Mission aborted by user.")
        finally:
            self.cleanup()
            
    def cleanup(self):
        self.motors.cleanup()
        self.servo.cleanup()
        self.vision.stop()
        import RPi.GPIO as GPIO
        GPIO.cleanup()
        print("System safely shut down.")

if __name__ == "__main__":
    rover = AutonomousRover()
    rover.run()
